function _clean_pi_usage --description "Print clean_pi usage"
  _ui title "Usage: clean_pi [MODE] [ROOT] [options]"
  _ui title "Modes (default: project)"
  _ui item "project: remove every .pi and .agents under ROOT and their Pi sessions"
  _ui item "skills: remove every .pi/skills and .agents/skills under ROOT"
  _ui item "agents: remove every .pi/agents and .agents/agents under ROOT"
  _ui item "purge: remove project directories under HOME, the global Pi agent directory"
  _ui note "and ~/.agents/skills (but not other shared ~/.agents contents)"
  _ui title "Options"
  _ui item "-n, --dry-run: list what would go, remove nothing"
  _ui item "-e, --exclude PATTERN: skip an extra directory name (repeatable)"
  _ui item "-i, --include PATTERN: stop skipping a default-excluded name"
  _ui item "-w, --worktree-config: ignored by Pi (accepted for clean:ai aliases)"
  _ui item "-h, --help: this text"
  _ui note "ROOT defaults to the current directory, or to \$HOME for purge."
  _ui note "Project sessions are selected by their recorded cwd in the configured session directory."
  _ui note "Sessions stored elsewhere with --session-dir or nested-project settings are not discovered."
  _ui note "Project trust in the global trust.json is not changed."
  _ui note "Dependency, cache and build trees are skipped; CLEAN_CLAUDE_EXCLUDES extends the list."
  _ui note "Only purge may remove global Pi configuration and shared skills."
end
