# Ansible playbook to manage setup of Arch Linux
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)

- name: Dotfiles
  hosts: all
  roles:
    - role: system
    - role: ssh
  vars_files:
    - vars/secrets.yml