# Ansible playbook to manage setup of macOS
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)

- name: Dotfiles
  hosts: all
  vars_files:
    - vars/secrets.yml
    - vars/work.yml

  roles:
    - role: brew
    - role: system
    - role: shell
    - role: ssh
    - role: user
    - role: apps
    - role: security
    - role: work
    - role: cleanup
    - role: reboot
