# Ansible playbook to manage setup of macOS
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)

- name: Dotfiles
  hosts: all
  vars_files:
    - vars/secrets.yml
    - vars/work.yml

  roles:
    - role: brew
      tags: [brew]
    - role: system
      tags: [system]
    - role: shell
      tags: [shell]
    - role: ssh
      tags: [ssh]
    - role: user
      tags: [user]
    - role: apps
      tags: [apps]
    - role: security
      tags: [security]
    - role: work
      tags: [work]
    - role: cleanup
      tags: [cleanup]
    - role: reboot
      tags: [reboot]
