# Ansible playbook to update firmware from Lenovo
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)

- name: Firmware
  hosts: all
  roles:
    - role: thinkpad
  vars_files:
    - vars/secrets.yml