# Ansible role to configure all related to the user
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Creating user directories
  ansible.builtin.file:
    path: "{{ HOME }}/{{ item }}"
    state: directory
    recurse: true
  with_items:
    - pictures
    - downloads
    - developer

- name: Linking all wallpapers
  ansible.builtin.file:
    src: "{{ role_path }}/files/wallpapers"
    dest: "{{ HOME }}/pictures/wallpapers"
    state: link
    force: true