# Ansible role to remove unnecessary dependencies and clear cache
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Remove unused Homebrew dependencies
  ansible.builtin.command: brew autoremove
  register: brew_autoremove
  changed_when: brew_autoremove.stdout != ""

- name: Prune Homebrew cache
  ansible.builtin.command: brew cleanup --prune=all
  register: brew_prune
  changed_when: brew_prune.stdout != ""

- name: Remove old Homebrew versions
  ansible.builtin.command: brew cleanup
  register: brew_cleanup
  changed_when: brew_cleanup.stdout != ""
