# Ansible vars to use with the apps role
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

BROWSERS_APPS:
  - --cask google-chrome
  - --cask zen-browser
  - --cask arc
  - --cask brave-browser


CHAT_APPS:
  - --cask slack
  - --cask discord

DEVELOPMENT_APPS:
  - httpie
  - git
  - git-delta
  - lazygit
  - fnm
  - scc
  - hyperfine

AI_APPS:
  - --cask chatgpt
  - --cask cursor

DATABASE_APPS:
  - libpq
  - pgcli
  - --cask dbeaver-community

EDITORS_APPS:
  - --cask visual-studio-code
  - --cask zed

INFRASTRUCTURE_APPS:
  # - ansible
  - awscli
  - docker
  - docker-compose
  - docker-buildx

MULTIMEDIA_APPS:
  - mpv
  - --cask spotify

SYSTEM_APPS:
  - --cask nikitabobko/tap/aerospace
  - --cask font-fira-code-nerd-font
  # - noto-fonts-emoji

OTHER_TOOLS:
  - nnn
