# Ansible vars to use with the apps role
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

BROWSERS_APPS:
  - google-chrome
  - zen-browser-avx2-bin
  - zen-browser
  - brave-bin
  - firefox-developer-edition

CHAT_APPS:
  - slack-desktop
  - discord

DEVELOPMENT_APPS:
  - httpie
  - git
  - github-cli
  - git-delta
  - fnm-bin
  - scc-bin
  - hyperfine

DATABASE_APPS:
  - pgcli

EDITORS_APPS:
  - visual-studio-code-bin
  - zed

INFRASTRUCTURE_APPS:
  - ansible
  - docker
  - docker-compose
  - docker-buildx

MULTIMEDIA_APPS:
  - mpv
  - spotify

SECURITY_APPS:
  - firejail

OTHER_TOOLS:
  - nnn

SYSTEM:
  - balena-etcher
  - noto-fonts-emoji
