# Ansible role to install all packages related to the system
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Load variables
  ansible.builtin.include_vars: vars/main.yml

- name: Creating user config directory
  ansible.builtin.file:
    path: "{{ HOME }}/.config"
    state: directory
    mode: "0755"

- name: Install all packages related to the system
  community.general.homebrew:
    name: "{{ SYSTEM_APPS }}"
    state: present

- name: Ensure bat config directory exists
  ansible.builtin.file:
    path: "{{ HOME }}/.config/bat"
    state: directory
    mode: "0755"

- name: Configuring bat
  ansible.builtin.file:
    src: "{{ role_path }}/files/bat/config"
    dest: "{{ HOME }}/.config/bat/config"
    state: link
    force: true

- name: Ensure ripgrep config directory exists
  ansible.builtin.file:
    path: "{{ HOME }}/.config/ripgrep"
    state: directory
    mode: "0755"

- name: Configuring ripgrep
  ansible.builtin.file:
    src: "{{ role_path }}/files/ripgrep/config"
    dest: "{{ HOME }}/.config/ripgrep/config"
    state: link
    force: true

- name: Ensure eza config directory exists
  ansible.builtin.file:
    path: "{{ HOME }}/.config/eza"
    state: directory
    mode: "0755"

- name: Configuring eza
  ansible.builtin.file:
    src: "{{ role_path }}/files/eza/theme.yml"
    dest: "{{ HOME }}/.config/eza/theme.yml"
    state: link
    force: true

- name: Setting the system preferences
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
  loop: "{{ OSX_DEFAULTS }}"

- name: Removing sound effect on boot # noqa: command-instead-of-shell
  become: true
  ansible.builtin.shell: nvram SystemAudioVolume=" "

# - name: Disable local Time Machine snapshots
#   become: true
#   ansible.builtin.shell: tmutil disablelocal

- name: Disable hibernation (speeds up entering sleep mode)
  become: true
  ansible.builtin.command: pmset -a hibernatemode 0

- name: Remove the sleep image file and prevent recreation
  become: true
  ansible.builtin.shell: |
    rm -f /Private/var/vm/sleepimage
    touch /Private/var/vm/sleepimage
    chflags uchg /Private/var/vm/sleepimage

- name: Disable the sudden motion sensor as it's not useful for SSDs
  become: true
  ansible.builtin.command: pmset -a sms 0

# - name: Show the ~/Library folder
#   ansible.builtin.shell: |
#     xattr -d com.apple.FinderInfo ~/Library 2>/dev/null
#     chflags nohidden ~/Library

# - name: Enable TRIM
#   become: true
#   ansible.builtin.shell: trimforce enable
