# Ansible defaults for the coreutils role
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)

---

HOSTOF:
  repository: https://github.com/jmanuelrosa/hostof
  release: v0.1.0
  checksum: sha256:32f6d3e413f77248802f371522c13be53bde8b0da49be5a64e6c609260ec0387

BREW_PACKAGES:
  formulas:
    - bat
    - btop
    - duf
    - eza
    - fastfetch
    - fd
    - httpie
    - hyperfine
    - nnn
    - ripgrep
    - scc
    - television
    - vnstat
    - wget
    - zoxide
    - unar
