"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 1000

# Theme
format = """
$directory\
$nodejs\
$custom\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[sudo]
style = 'bold yellow'
symbol = '🧙'
disabled = false

[aws]
disabled = true

[cmd_duration]
disabled = false

[memory_usage]
disabled=true

[directory]
style = "bold cyan"
truncate_to_repo = false
truncation_length = 5
read_only = " 󰌾"
truncation_symbol = "…/"

[directory.substitutions]
"~/Developer/work/didomi" = "@didomi"
"~/Developer/work/addingwell" = "@addingwell"
"~/Developer/dotfiles" = "@dotfiles"
"~/Developer/personal" = "@personal"
"~/Developer/3bitslost" = "@3bitslost"

[docker_context]
disabled = true

[gcloud]
disabled = true

[git_state]
disabled=false

[git_branch]
symbol = " "
format = "on [$branch(:$remote_branch)]($style) "
style = "bold purple"

[git_metrics]
disabled = false

[git_status]
format = '([$modified]($style) )'
style = "bold red"
# ahead = '🏎💨'
ahead = ""
behind = '⇣'
# conflicted = '🏳'
conflicted = ""
# deleted = '🗑'
deleted = ""
diverged = "⇕⇡"
modified = "~"
renamed = ""
# renamed = "»${count}"
staged = "+"
stashed = '📦'
# stashed = "≡${count}"
untracked = '~'
# untracked = "…${count}"
up_to_date = '✓'

[line_break]
disabled = false

[mise]
disabled = true

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold green"
detect_files = ["package.json", ".node-version", ".nvmrc"]
detect_folders = ["node_modules"]

[custom.pnpm]
detect_files = ["pnpm-lock.yaml"]
symbol = "\U000f0ab5 "
command = "echo pnpm"
format = "[$symbol($output )]($style)"
style = "bold #f9f1e1"

[custom.bun]
detect_files = ["bun.lockb", "bun.lock"]
symbol = "🥟 "
command = "echo bun"
format = "[$symbol($output )]($style)"
style = "bold #f9f1e1"

[custom.npm]
detect_files = ["package-lock.json"]
symbol = " "
command = "echo npm"
format = "[$symbol($output )]($style)"
style = "bold #f9f1e1"

[custom.yarn]
detect_files = ["yarn.lock"]
symbol = " "
command = "echo yarn"
format = "[$symbol($output )]($style)"
style = "bold #f9f1e1"

