# Ansible vars to use with the system role
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)

---

SYSTEM_APPS:
  - bat
  - blueman
  - bluez
  - bluez-utils
  - duf
  - git
  - github-cli
  - glances
  - httpie
  - neofetch
  - p7zip
  - wget
  - tlp
  - tlp-rdw
  - lm_sensors
  - acpi_call-dkms