# Ansible vars to use with the system role
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)

---

SYSTEM_APPS:
  - bat
  - duf
  - github-cli
  - glances
  - httpie
  - neofetch
  - p7zip
  - wget