# Ansible role to configure all related to work
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Load work variables
  ansible.builtin.include_vars: vars/main.yml

- name: Tap Atlassian Homebrew repository
  community.general.homebrew_tap:
    name: atlassian/homebrew-acli
    state: present

- name: Install work formulas
  community.general.homebrew:
    name: "{{ WORK_FORMULAS }}"
    state: present

- name: Install work casks
  community.general.homebrew_cask:
    name: "{{ WORK_CASKS }}"
    state: present

- name: Generating exports with secrets
  ansible.builtin.template:
    src: exports.fish.j2
    dest: "{{ HOME }}/.config/fish/conf.d/work-secrets.fish"
    mode: "0600"

- name: Ensure scripts directory exists
  ansible.builtin.file:
    path: "{{ HOME }}/.config/fish/conf.d/scripts"
    state: directory
    mode: '0755'

- name: Link all scripts to config directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/scripts/{{ item | basename }}"
    dest: "{{ HOME }}/.local/bin/{{ item | basename }}"
    state: link
    force: true
  with_fileglob:
    - "{{ role_path }}/files/scripts/*"

- name: Ensure glab-cli config directory exists
  ansible.builtin.file:
    path: "{{ HOME }}/Library/Application Support/glab-cli"
    state: directory
    mode: "0755"

- name: Configuring glab
  ansible.builtin.copy:
    src: "{{ role_path }}/files/glab/config.yml"
    dest: "{{ HOME }}/Library/Application Support/glab-cli/config.yml"
    mode: "0644"
    force: true

- name: Creating SSH config directory
  ansible.builtin.file:
    path: "{{ HOME }}/.ssh"
    state: directory
    mode: "0700"

- name: Loading SSH private key
  ansible.builtin.copy:
    content: "{{ SSH_DIDOMI_KEY }}"
    dest: "{{ HOME }}/.ssh/id_didomi"
    owner: "{{ USER }}"
    mode: "0600"

- name: Loading SSH public key
  ansible.builtin.copy:
    content: "{{ SSH_DIDOMI_PUBLIC }}"
    dest: "{{ HOME }}/.ssh/id_didomi.pub"
    owner: "{{ USER }}"
    mode: "0644"
