# Ansible role to install and configure all browser apps
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Install browsers
  ansible.builtin.shell: yay --quiet --sync --noconfirm --removemake {{ item }}
  loop: "{{ BROWSERS_APPS }}"