
# Ansible role to install and configure all development apps
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Install development apps
  ansible.builtin.shell: yay --quiet --sync --noconfirm --removemake {{ item }}
  loop: "{{ DEVELOPMENT_APPS }}"

- name: Install databases apps
  ansible.builtin.shell: yay --quiet --sync --noconfirm --removemake {{ item }}
  loop: "{{ DATABASE_APPS }}"
