# Ansible role to install and configure all infrastructure apps
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Install infrastructure apps
  community.general.pacman:
    name: "{{ item }}"
    state: present
    executable: yay
    extra_args: --noconfirm
  loop: "{{ INFRASTRUCTURE_APPS }}"
