# Ansible role to install and configure all infrastructure apps
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Link docker formula
  ansible.builtin.command: brew link docker
  register: docker_link
  changed_when: "'Linking' in docker_link.stdout"
  failed_when: docker_link.rc != 0 and 'Already linked' not in docker_link.stderr

- name: Symlink docker config
  ansible.builtin.file:
    src: "{{ role_path }}/files/docker/config.json"
    dest: "{{ HOME }}/.docker/config.json"
    state: link
    force: true

- name: Ensure ctop config directory exists
  ansible.builtin.file:
    path: "{{ HOME }}/.config/ctop"
    state: directory
    mode: "0755"

- name: Symlink ctop config
  ansible.builtin.file:
    src: "{{ role_path }}/files/ctop/config"
    dest: "{{ HOME }}/.config/ctop/config"
    state: link
    force: true
