# Ansible role to install and configure all multimedia apps
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Install multimedia apps
  ansible.builtin.shell: yay --quiet --sync --noconfirm --removemake {{ item }}
  loop: "{{ MULTIMEDIA_APPS }}"


