# Ansible role to install and configure all development apps
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Load system variables
  ansible.builtin.include_vars: vars/main.yml

- name: Install npm packages
  ansible.builtin.command: "bun install -g {{ item }}"
  loop: "{{ NPM_PACKAGES }}"
