# Ansible role to install and configure system apps
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Symlink aerospace config
  ansible.builtin.file:
    src: "{{ role_path }}/files/.aerospace.toml"
    dest: "{{ HOME }}/.aerospace.toml"
    state: link
    force: true
