# Ansible role to configure all related to sway desktop
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Install all window manager and wm apps
  ansible.builtin.shell: yay --quiet --sync --noconfirm --removemake {{ item }}
  loop: "{{ SWAY_APPS }}"
  register: result
  changed_when:
    - result.failed

- name: Creating backup directory for sway
  ansible.builtin.file:
    path: "backups/{{ item }}"
    state: directory
    recurse: true
  with_items:
    - .config/sway
    - .config/waybar

- name: Check if files to backup exists
  stat:
    path: "{{ HOME }}/{{ item }}"
  with_items:
    - .config/sway/config
    - .config/waybar/config
    - .config/waybar/style.css
  register: results

- name: Backup sway settings
  ansible.builtin.copy:
    src: "{{ item.stat.path }}"
    dest: "{{ CURRENT_DIR }}/backups/{{ item.item }}"
  when: item.stat.exists == True
  with_items: "{{ results.results }}"

- name: Creating directory for sway settings
  ansible.builtin.file:
    path: "{{ HOME }}/.config/sway/"
    state: directory
    recurse: true

- name: Creating directory for waybar settings
  ansible.builtin.file:
    path: "{{ HOME }}/.config/waybar/"
    state: directory
    recurse: true

- name: Configuring Sway
  ansible.builtin.file:
    src: "{{ role_path }}/files/sway/config"
    dest: "{{ HOME }}/.config/sway/config"
    state: link
    force: true

- name: Configuring Waybar
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ HOME }}/.config/{{ item }}"
    state: link
    force: true
  with_items:
    - waybar/config
    - waybar/style.css
